version: '3'
services:
  jekyll:
    image: jekyll/builder:latest
    #environment:
    #  - "JEKYLL_GITHUB_TOKEN:${JEKYLL_GITHUB_TOKEN}"
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - C:\\repos\\beautiful-jekyll:/srv/jekyll

    command: jekyll serve --drafts --force-polling --livereload